PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTM_PERMISOSCT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTM_PERMISOSCT-NAME .
    FIELD ZTM_PERMISOSCT-TEXT .
    FIELD ZTM_PERMISOSCT-PERMISOSCT .
    FIELD ZTM_PERMISOSCT-CHANGEUSER .
    FIELD ZTM_PERMISOSCT-CHANGEDATE .
    FIELD ZTM_PERMISOSCT-CHANGEHOUR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTM_PERMISOSCT-NAME .
    FIELD ZTM_PERMISOSCT-TEXT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
